name: AWS Deploy

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Run Sam validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Sam validation
        run: sam validate --template template.yaml
        working-directory: backend

  deploy:
    name: Deploy SAM Stack
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: test # 🔐 Only runs if 'test' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: backend/src/budget-buddy-api

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: backend/src/statement-processor

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build SAM project
        run: sam build --template template.yaml
        working-directory: backend

      - name: Deploy SAM stack
        run: sam deploy --template template.yaml --no-fail-on-empty-changeset --debug
        working-directory: backend
